apiVersion: v1
kind: Secret
metadata:
  name: google-llm-secret
  namespace: emergent
  labels:
    app: emergent
type: Opaque
stringData:
  EMERGENT_LLM_KEY: "AIzaSyAmSWtYQtkKeXRIYyJua28jWlzeAXFZYHk"
