import {
  VitalisDataProvider,
  VitalisLiveRequestsFilter,
  VitalisInvestigationRequest,
} from './interface';
import {
  VitalisCommandCenterOverview,
  VitalisRequest,
  VitalisInventoryItem,
  VitalisScenario,
} from '../domain/types';

export const DEMO_ENTERPRISE_SCENARIOS: VitalisScenario[] = [
  {
    id: 'SCENARIO_1_NOMINAL',
    scenarioNumber: 1,
    name: 'Normal Payment Processing',
    tagline: 'Standard production baseline transaction flow',
    description: 'All 11 enterprise pipeline tiers operating nominally. DB2 query P95 at 4ms.',
    status: 'NOMINAL',
    operationalScore: 100,
    p95LatencyMs: 25,
    slaPercent: 100,
    errorCount: 0,
    businessImpact: {
      status: 'PROTECTED',
      provenance: 'SIMULATED',
      monitoredUsers: 12458,
      failedTransactions: 0,
      estimatedFinancialExposure: '₹0.00',
      impactedService: 'PaymentGateway',
      slaCompliancePercent: 100,
      summary: 'All customer checkout pipelines operating within nominal parameters.',
      sourceNote: 'Simulated baseline telemetry from 11 enterprise nodes.',
    },
    journey: [
      { name: 'Browser Client', kind: 'CLIENT', time: '8 ms', status: 'HEALTHY' },
      { name: 'Enterprise DNS', kind: 'DNS', time: '2 ms', status: 'HEALTHY' },
      { name: 'Core Network', kind: 'NETWORK', time: '1 ms', status: 'HEALTHY' },
      { name: 'Border Firewall', kind: 'FIREWALL', time: '2 ms', status: 'HEALTHY' },
      { name: 'F5 BIG-IP Load Balancer', kind: 'LOAD_BALANCER', time: '3 ms', status: 'HEALTHY' },
      { name: 'IBM HTTP Server (IHS)', kind: 'WEB_SERVER', time: '4 ms', status: 'HEALTHY' },
      { name: 'IBM WebSphere App Server', kind: 'APP_SERVER', time: '6 ms', status: 'HEALTHY' },
      { name: 'IBM MQ Message Broker', kind: 'MESSAGE_QUEUE', time: '3 ms', status: 'HEALTHY' },
      { name: 'IBM DB2 Enterprise Database', kind: 'DATABASE', time: '4 ms', status: 'HEALTHY' },
      { name: 'Payment Settlement Gateway', kind: 'DOWNSTREAM', time: '12 ms', status: 'HEALTHY' },
      { name: 'Client HTTP 200 OK', kind: 'RESPONSE', time: '1 ms', status: 'HEALTHY' },
    ],
    causalStory: [
      {
        id: 'STEP_1',
        stepNumber: 1,
        nodeName: 'IBM DB2 Database',
        tier: 'DATABASE',
        changeOrSignal: 'DB2_MAX_LOCKS = 120000',
        timestamp: '09:00:00',
        observedEffect: 'Lock table capacity optimal; 0 lock waits recorded.',
        evidenceTitle: 'DB2 Bufferpool & Lock Table Audit',
        evidenceSnippet: 'SELECT LOCKS_HELD, LOCK_ESCALATION FROM SYSIBMADM.SNAPLOCKWAIT -> 0 records.',
        evidenceType: 'CONFIG_AUDIT',
        confidencePercent: 99,
      },
    ],
    rca: {
      summary: 'Healthy baseline operations. No remediation required.',
      rootCauseNode: 'ALL_NODES_HEALTHY',
      confidencePercent: 99,
      recommendedAction: 'Maintain current configuration baseline.',
    },
  },
  {
    id: 'SCENARIO_2_MTU_MISMATCH',
    scenarioNumber: 2,
    name: 'Network MTU Mismatch',
    tagline: 'Packet fragmentation causing latency degradation between F5 and IHS',
    description: 'F5 MTU configured at 1500 bytes while switch port enforces 1400 bytes, forcing IP fragmentation.',
    status: 'DEGRADED',
    operationalScore: 78,
    p95LatencyMs: 380,
    slaPercent: 91,
    errorCount: 14,
    businessImpact: {
      status: 'ATTENTION_REQUIRED',
      provenance: 'SIMULATED',
      monitoredUsers: 1420,
      failedTransactions: 14,
      estimatedFinancialExposure: '₹45,000',
      impactedService: 'EdgeIngress',
      slaCompliancePercent: 91.2,
      summary: '14 transactions degraded due to packet fragmentation at ingress boundary.',
      sourceNote: 'Simulated packet header telemetry.',
    },
    journey: [
      { name: 'Browser Client', kind: 'CLIENT', time: '8 ms', status: 'HEALTHY' },
      { name: 'Enterprise DNS', kind: 'DNS', time: '2 ms', status: 'HEALTHY' },
      { name: 'Core Network', kind: 'NETWORK', time: '180 ms', status: 'DEGRADED', anomalyNote: 'MTU mismatch: 1500 vs 1400' },
      { name: 'Border Firewall', kind: 'FIREWALL', time: '4 ms', status: 'HEALTHY' },
      { name: 'F5 BIG-IP Load Balancer', kind: 'LOAD_BALANCER', time: '140 ms', status: 'DEGRADED', anomalyNote: 'Packet retransmission' },
      { name: 'IBM HTTP Server (IHS)', kind: 'WEB_SERVER', time: '20 ms', status: 'HEALTHY' },
      { name: 'IBM WebSphere App Server', kind: 'APP_SERVER', time: '15 ms', status: 'HEALTHY' },
      { name: 'IBM MQ Message Broker', kind: 'MESSAGE_QUEUE', time: '4 ms', status: 'HEALTHY' },
      { name: 'IBM DB2 Enterprise Database', kind: 'DATABASE', time: '5 ms', status: 'HEALTHY' },
      { name: 'Payment Settlement Gateway', kind: 'DOWNSTREAM', time: '14 ms', status: 'HEALTHY' },
      { name: 'Client Response', kind: 'RESPONSE', time: '1 ms', status: 'HEALTHY' },
    ],
    causalStory: [
      {
        id: 'STEP_1',
        stepNumber: 1,
        nodeName: 'Core Switch SW-01',
        tier: 'NETWORK',
        changeOrSignal: 'Interface MTU changed to 1400 bytes',
        timestamp: '08:45:12',
        observedEffect: 'F5 packets > 1400 bytes fragmented; TCP retransmissions jumped +340%.',
        evidenceTitle: 'Switch Interface Config Audit & TCP Dump',
        evidenceSnippet: 'ifconfig eth0 mtu 1400; tcpdump: IP (frag 41201:1400@0+) -> TCP Retransmission',
        evidenceType: 'CONFIG_AUDIT',
        confidencePercent: 96,
      },
    ],
    rca: {
      summary: 'Network interface MTU mismatch between F5 Load Balancer and Core Switch.',
      rootCauseNode: 'Core Switch SW-01',
      confidencePercent: 96,
      recommendedAction: 'Standardize Interface MTU to 1500 bytes across all ingress switches.',
    },
  },
  {
    id: 'SCENARIO_3_JVM_OPTION',
    scenarioNumber: 3,
    name: 'WebSphere JVM Deprecated Option',
    tagline: 'Deprecated GC flag triggered Stop-The-World pause cascades',
    description: 'Migration script added unsupported -XX:+UseConcMarkSweepGC causing full GC stalls.',
    status: 'DEGRADED',
    operationalScore: 68,
    p95LatencyMs: 1450,
    slaPercent: 84,
    errorCount: 82,
    businessImpact: {
      status: 'ATTENTION_REQUIRED',
      provenance: 'SIMULATED',
      monitoredUsers: 3850,
      failedTransactions: 82,
      estimatedFinancialExposure: '₹1.8L',
      impactedService: 'WebSphereAppCluster',
      slaCompliancePercent: 84.5,
      summary: 'Recurring 1.4s GC pauses causing connection timeouts.',
      sourceNote: 'Simulated JVM verbosegc logs.',
    },
    journey: [
      { name: 'Browser Client', kind: 'CLIENT', time: '8 ms', status: 'HEALTHY' },
      { name: 'Enterprise DNS', kind: 'DNS', time: '2 ms', status: 'HEALTHY' },
      { name: 'Core Network', kind: 'NETWORK', time: '1 ms', status: 'HEALTHY' },
      { name: 'Border Firewall', kind: 'FIREWALL', time: '2 ms', status: 'HEALTHY' },
      { name: 'F5 BIG-IP Load Balancer', kind: 'LOAD_BALANCER', time: '4 ms', status: 'HEALTHY' },
      { name: 'IBM HTTP Server (IHS)', kind: 'WEB_SERVER', time: '6 ms', status: 'HEALTHY' },
      { name: 'IBM WebSphere App Server', kind: 'APP_SERVER', time: '1240 ms', status: 'CRITICAL', anomalyNote: 'Stop-The-World Full GC pause' },
      { name: 'IBM MQ Message Broker', kind: 'MESSAGE_QUEUE', time: '8 ms', status: 'HEALTHY' },
      { name: 'IBM DB2 Enterprise Database', kind: 'DATABASE', time: '6 ms', status: 'HEALTHY' },
      { name: 'Payment Settlement Gateway', kind: 'DOWNSTREAM', time: '15 ms', status: 'HEALTHY' },
      { name: 'Client Response', kind: 'RESPONSE', time: '2 ms', status: 'HEALTHY' },
    ],
    causalStory: [
      {
        id: 'STEP_1',
        stepNumber: 1,
        nodeName: 'WebSphere server.xml',
        tier: 'APP_SERVER',
        changeOrSignal: 'genericJvmArguments += "-XX:+UseConcMarkSweepGC"',
        timestamp: '09:10:00',
        observedEffect: 'Java 17 runtime ignores flag; defaults to Serial GC fallback under load.',
        evidenceTitle: 'WebSphere server.xml & native_stderr.log',
        evidenceSnippet: 'native_stderr.log: [GC (Allocation Failure) [Full GC (Ergonomics) 1420ms]]',
        evidenceType: 'THREAD_DUMP',
        confidencePercent: 94,
      },
    ],
    rca: {
      summary: 'Deprecated CMS GC flag on modern JVM forcing single-threaded Full GC pauses.',
      rootCauseNode: 'IBM WebSphere App Server',
      confidencePercent: 94,
      recommendedAction: 'Remove deprecated GC argument and configure -XX:+UseG1GC.',
    },
  },
  {
    id: 'SCENARIO_4_MQ_CHANNEL',
    scenarioNumber: 4,
    name: 'IBM MQ Channel Cipher Mismatch',
    tagline: 'TLS 1.3 handshake negotiation failure on payment queue channel',
    description: 'Security patch disabled TLS_RSA ciphers on MQ queue manager, rejecting WebSphere client channels.',
    status: 'CRITICAL',
    operationalScore: 42,
    p95LatencyMs: 4200,
    slaPercent: 62,
    errorCount: 420,
    businessImpact: {
      status: 'ATTENTION_REQUIRED',
      provenance: 'SIMULATED',
      monitoredUsers: 6400,
      failedTransactions: 420,
      estimatedFinancialExposure: '₹4.8L',
      impactedService: 'PaymentMessaging',
      slaCompliancePercent: 62.0,
      summary: 'Payment messages unable to reach settlement queue. Channel disconnected.',
      sourceNote: 'Simulated IBM MQ AMQERR01.LOG.',
    },
    journey: [
      { name: 'Browser Client', kind: 'CLIENT', time: '8 ms', status: 'HEALTHY' },
      { name: 'Enterprise DNS', kind: 'DNS', time: '2 ms', status: 'HEALTHY' },
      { name: 'Core Network', kind: 'NETWORK', time: '1 ms', status: 'HEALTHY' },
      { name: 'Border Firewall', kind: 'FIREWALL', time: '2 ms', status: 'HEALTHY' },
      { name: 'F5 BIG-IP Load Balancer', kind: 'LOAD_BALANCER', time: '4 ms', status: 'HEALTHY' },
      { name: 'IBM HTTP Server (IHS)', kind: 'WEB_SERVER', time: '5 ms', status: 'HEALTHY' },
      { name: 'IBM WebSphere App Server', kind: 'APP_SERVER', time: '80 ms', status: 'DEGRADED' },
      { name: 'IBM MQ Message Broker', kind: 'MESSAGE_QUEUE', time: '3800 ms', status: 'CRITICAL', anomalyNote: 'AMQ9631: CipherSpec negotiation failed' },
      { name: 'IBM DB2 Enterprise Database', kind: 'DATABASE', time: '4 ms', status: 'HEALTHY' },
      { name: 'Payment Settlement Gateway', kind: 'DOWNSTREAM', time: '12 ms', status: 'HEALTHY' },
      { name: 'Client Response (500)', kind: 'RESPONSE', time: '1 ms', status: 'CRITICAL' },
    ],
    causalStory: [
      {
        id: 'STEP_1',
        stepNumber: 1,
        nodeName: 'IBM MQ QM_PAYMENT',
        tier: 'MESSAGE_QUEUE',
        changeOrSignal: 'ALTER QMGR SSLEVR(TLS13)',
        timestamp: '09:22:15',
        observedEffect: 'WebSphere SVRCONN channel rejected: SSLCIPH mismatch.',
        evidenceTitle: 'IBM MQ Error Log (AMQERR01.LOG)',
        evidenceSnippet: 'AMQ9631: The CipherSpec negotiated during SSL handshake does not match the required CipherSpec.',
        evidenceType: 'QUEUE_LOG',
        confidencePercent: 98,
      },
    ],
    rca: {
      summary: 'TLS CipherSpec mismatch between WebSphere JMS connection factory and MQ Queue Manager.',
      rootCauseNode: 'IBM MQ Message Broker',
      confidencePercent: 98,
      recommendedAction: 'Update WebSphere JMS CipherSuite to TLS_AES_256_GCM_SHA384.',
    },
  },
  {
    id: 'SCENARIO_5_DB2_CODEPAGE',
    scenarioNumber: 5,
    name: 'DB2 Code Page 1208 Mismatch',
    tagline: 'UTF-8 string expansion causing SQL0302N field overflow',
    description: 'Application server client sent multi-byte UTF-8 characters exceeding DB2 VARCHAR column limits.',
    status: 'DEGRADED',
    operationalScore: 58,
    p95LatencyMs: 980,
    slaPercent: 76,
    errorCount: 215,
    businessImpact: {
      status: 'ATTENTION_REQUIRED',
      provenance: 'SIMULATED',
      monitoredUsers: 2150,
      failedTransactions: 215,
      estimatedFinancialExposure: '₹2.1L',
      impactedService: 'CustomerProfile',
      slaCompliancePercent: 76.4,
      summary: 'Character encoding expansion causing database insert rejection.',
      sourceNote: 'Simulated DB2 db2diag.log.',
    },
    journey: [
      { name: 'Browser Client', kind: 'CLIENT', time: '8 ms', status: 'HEALTHY' },
      { name: 'Enterprise DNS', kind: 'DNS', time: '2 ms', status: 'HEALTHY' },
      { name: 'Core Network', kind: 'NETWORK', time: '1 ms', status: 'HEALTHY' },
      { name: 'Border Firewall', kind: 'FIREWALL', time: '2 ms', status: 'HEALTHY' },
      { name: 'F5 BIG-IP Load Balancer', kind: 'LOAD_BALANCER', time: '3 ms', status: 'HEALTHY' },
      { name: 'IBM HTTP Server (IHS)', kind: 'WEB_SERVER', time: '4 ms', status: 'HEALTHY' },
      { name: 'IBM WebSphere App Server', kind: 'APP_SERVER', time: '24 ms', status: 'HEALTHY' },
      { name: 'IBM MQ Message Broker', kind: 'MESSAGE_QUEUE', time: '4 ms', status: 'HEALTHY' },
      { name: 'IBM DB2 Enterprise Database', kind: 'DATABASE', time: '880 ms', status: 'CRITICAL', anomalyNote: 'SQL0302N: Value too large for column' },
      { name: 'Payment Settlement Gateway', kind: 'DOWNSTREAM', time: '12 ms', status: 'HEALTHY' },
      { name: 'Client Response (500)', kind: 'RESPONSE', time: '1 ms', status: 'CRITICAL' },
    ],
    causalStory: [
      {
        id: 'STEP_1',
        stepNumber: 1,
        nodeName: 'IBM DB2 Database',
        tier: 'DATABASE',
        changeOrSignal: 'DB2CODEPAGE = 1208 (UTF-8)',
        timestamp: '09:30:00',
        observedEffect: 'VARCHAR(50) byte limit exceeded by 3-byte unicode characters.',
        evidenceTitle: 'DB2 Diagnostic Log (db2diag.log)',
        evidenceSnippet: 'MESSAGE : ZRC=0x80100024=-2146435036=SQLO_CHAR_OVERFLOW "Data value overflow for host variable"',
        evidenceType: 'ERROR_TRACE',
        confidencePercent: 95,
      },
    ],
    rca: {
      summary: 'Character encoding expansion from single-byte to UTF-8 overflowing VARCHAR schema allocations.',
      rootCauseNode: 'IBM DB2 Enterprise Database',
      confidencePercent: 95,
      recommendedAction: 'Alter column definitions from VARCHAR(n OCTETS) to VARCHAR(n CODEUNITS32).',
    },
  },
  {
    id: 'SCENARIO_6_LOCK_CONTENTION',
    scenarioNumber: 6,
    name: 'DB2 Lock Contention (Master Incident)',
    tagline: 'DB2_MAX_LOCKS reduction triggered massive lock escalations & cascading thread starvation',
    description: 'Production hotfix accidentally changed DB2_MAX_LOCKS from 120,000 to 50,000, inducing row-to-table lock escalation, +847% lock contention, WebSphere thread pool saturation, and 1,545 payment checkout failures.',
    status: 'CRITICAL',
    operationalScore: 24,
    p95LatencyMs: 8640,
    slaPercent: 48,
    errorCount: 1545,
    businessImpact: {
      status: 'ATTENTION_REQUIRED',
      provenance: 'SIMULATED',
      monitoredUsers: 12458,
      failedTransactions: 1545,
      estimatedFinancialExposure: '₹12.5L',
      impactedService: 'PaymentProcessing',
      slaCompliancePercent: 48.2,
      summary: '1,545 customer payment failures. Total revenue exposure estimated at ₹12.5 Lakhs.',
      sourceNote: 'Simulated Master Incident telemetry derived from IBM DB2 and WebSphere telemetry traces.',
    },
    journey: [
      { name: 'Browser Client', kind: 'CLIENT', time: '8 ms', status: 'HEALTHY' },
      { name: 'Enterprise DNS', kind: 'DNS', time: '2 ms', status: 'HEALTHY' },
      { name: 'Core Network', kind: 'NETWORK', time: '2 ms', status: 'HEALTHY' },
      { name: 'Border Firewall', kind: 'FIREWALL', time: '3 ms', status: 'HEALTHY' },
      { name: 'F5 BIG-IP Load Balancer', kind: 'LOAD_BALANCER', time: '5 ms', status: 'HEALTHY' },
      { name: 'IBM HTTP Server (IHS)', kind: 'WEB_SERVER', time: '12 ms', status: 'HEALTHY' },
      { name: 'IBM WebSphere App Server', kind: 'APP_SERVER', time: '2800 ms', status: 'CRITICAL', anomalyNote: 'Thread pool 92% saturated' },
      { name: 'IBM MQ Message Broker', kind: 'MESSAGE_QUEUE', time: '1400 ms', status: 'DEGRADED', anomalyNote: '1,214 messages queued' },
      { name: 'IBM DB2 Enterprise Database', kind: 'DATABASE', time: '4120 ms', status: 'CRITICAL', anomalyNote: 'Lock contention +847% (LOCK_ESCALATION)' },
      { name: 'Payment Settlement Gateway', kind: 'DOWNSTREAM', time: '280 ms', status: 'HEALTHY' },
      { name: 'Client HTTP 500 Error', kind: 'RESPONSE', time: '1 ms', status: 'CRITICAL' },
    ],
    causalStory: [
      {
        id: 'STEP_1',
        stepNumber: 1,
        nodeName: 'DB2 Database Configuration',
        tier: 'DATABASE',
        changeOrSignal: 'DB2_MAX_LOCKS: 120000 ➔ 50000',
        timestamp: '09:12:43',
        observedEffect: 'Maximum lock allocation per application reduced by 58.3%.',
        evidenceTitle: 'DB2 Configuration Audit Log',
        evidenceSnippet: 'UPDATE DBM CFG USING MAXLOCKS 50000; -- Executed by db2inst1 at 09:12:43',
        evidenceType: 'CONFIG_AUDIT',
        confidencePercent: 99,
      },
      {
        id: 'STEP_2',
        stepNumber: 2,
        nodeName: 'DB2 Lock Subsystem',
        tier: 'DATABASE',
        changeOrSignal: 'Lock Escalation Triggered (+847%)',
        timestamp: '09:34:30',
        observedEffect: 'Row-level locks automatically escalated to exclusive table-level locks.',
        evidenceTitle: 'DB2 Lock Wait Snapshot',
        evidenceSnippet: 'SELECT LOCK_MODE, TABNAME, LOCK_WAIT_ELAPSED_TIME FROM SYSIBMADM.SNAPLOCKWAIT -> Table X-Lock on PAYMENT_TXN',
        evidenceType: 'METRIC_SPIKE',
        confidencePercent: 97,
      },
      {
        id: 'STEP_3',
        stepNumber: 3,
        nodeName: 'DB2 Query Latency',
        tier: 'DATABASE',
        changeOrSignal: 'DB2 P95 Latency: 420ms ➔ 3.5s (+734%)',
        timestamp: '09:34:55',
        observedEffect: 'Database transactions blocked waiting for release of exclusive table locks.',
        evidenceTitle: 'DB2 Statement Performance Metrics',
        evidenceSnippet: 'SQL Statement: UPDATE PAYMENT_TXN SET STATUS = "APPROVED" WHERE ID = ? -> Avg Exec Time 3540ms',
        evidenceType: 'METRIC_SPIKE',
        confidencePercent: 96,
      },
      {
        id: 'STEP_4',
        stepNumber: 4,
        nodeName: 'WebSphere Application Server',
        tier: 'APP_SERVER',
        changeOrSignal: 'Thread Pool Saturation: 92%',
        timestamp: '09:35:10',
        observedEffect: 'Servlet execution threads blocked waiting on JDBC database connection return.',
        evidenceTitle: 'WebSphere Javacore Thread Dump',
        evidenceSnippet: 'Thread "WebContainer : 42" state:WAITING on com.ibm.db2.jcc.am.Connection.commit()',
        evidenceType: 'THREAD_DUMP',
        confidencePercent: 95,
      },
      {
        id: 'STEP_5',
        stepNumber: 5,
        nodeName: 'IBM MQ Message Queue',
        tier: 'MESSAGE_QUEUE',
        changeOrSignal: 'Queue Depth: 1,214 Pending Messages',
        timestamp: '09:36:05',
        observedEffect: 'Inbound checkout messages piled up as WebSphere consumers stopped draining the queue.',
        evidenceTitle: 'MQ Queue Depth & Inquire Logs',
        evidenceSnippet: 'DISPLAY QLOCAL(PAYMENT.INBOUND.QUEUE) CURDEPTH -> 1214 (MaxDepth 5000)',
        evidenceType: 'QUEUE_LOG',
        confidencePercent: 94,
      },
      {
        id: 'STEP_6',
        stepNumber: 6,
        nodeName: 'Client Checkout Gateway',
        tier: 'CLIENT',
        changeOrSignal: 'Payment Failures: 1,545 Transactions',
        timestamp: '09:37:00',
        observedEffect: 'HTTP 504 Gateway Timeout and 500 Internal Server Error returned to users.',
        evidenceTitle: 'Client Access & Ingress Error Trace',
        evidenceSnippet: 'POST /api/v1/checkout/pay -> 504 Gateway Timeout (Duration: 8.64s)',
        evidenceType: 'ERROR_TRACE',
        confidencePercent: 92,
      },
      {
        id: 'STEP_7',
        stepNumber: 7,
        nodeName: 'Business Revenue Impact',
        tier: 'BUSINESS',
        changeOrSignal: 'Financial Exposure: ₹12.5 Lakhs Across 12,458 Users',
        timestamp: '09:38:00',
        observedEffect: '12,458 customer checkout sessions interrupted during peak evening trading.',
        evidenceTitle: 'E-Commerce Order Funnel Telemetry',
        evidenceSnippet: 'Abandoned Carts: +412% | Failed Payments: ₹12,50,000 value across 1545 orders',
        evidenceType: 'METRIC_SPIKE',
        confidencePercent: 92,
      },
    ],
    rca: {
      summary: 'DB2 MAXLOCKS configuration change induced aggressive lock escalations, blocking database threads and saturating WebSphere application server worker pools.',
      rootCauseNode: 'IBM DB2 Database (DB2_MAX_LOCKS)',
      confidencePercent: 92,
      recommendedAction: 'Execute Runbook RB-DB2-042: Restore DB2_MAX_LOCKS to 120,000 and restart DB2 application engine.',
      runbookId: 'RB-DB2-042',
    },
  },
];

export class VitalisDemoDataProvider implements VitalisDataProvider {
  private activeScenario: VitalisScenario = DEMO_ENTERPRISE_SCENARIOS[5]; // Default to Scenario 6

  public setScenario(scenarioId: string) {
    const found = DEMO_ENTERPRISE_SCENARIOS.find((s) => s.id === scenarioId);
    if (found) {
      this.activeScenario = found;
    }
  }

  public getActiveScenario(): VitalisScenario {
    return this.activeScenario;
  }

  public async getCommandCenterOverview(): Promise<VitalisCommandCenterOverview> {
    const sc = this.activeScenario;
    return {
      operationalScore: sc.operationalScore,
      slaPercent: sc.slaPercent,
      p95LatencyMs: sc.p95LatencyMs,
      activeIncidentsCount: sc.status === 'NOMINAL' ? 0 : 1,
      totalRequestsCount: 1248,
      errorCount: sc.errorCount,
      environment: 'DEMO',
      provenance: 'SIMULATED',
      businessImpactDetail: sc.businessImpact,
      healthExplanation: {
        overallScore: sc.operationalScore,
        status: sc.status === 'NOMINAL' ? 'NOMINAL' : sc.status === 'DEGRADED' ? 'DEVIATION' : 'INCIDENT',
        reasons:
          sc.status === 'NOMINAL'
            ? [
                '✓ All 11 enterprise pipeline tiers healthy',
                '✓ No SLA breaches across live trace sample',
                '✓ No abnormal lock contention or queue depth',
                '✓ Zero active incidents',
              ]
            : [
                `🔴 ${sc.rca.summary}`,
                `⚠️ Confidence Score: ${sc.rca.confidencePercent}% HIGH`,
                `⚠️ Impacted Service: ${sc.businessImpact.impactedService}`,
              ],
        dimensions: [
          { name: 'Performance', score: sc.status === 'NOMINAL' ? 98 : 34, description: 'P95 latency & throughput stability', signalsCount: 14 },
          { name: 'Reliability', score: sc.status === 'NOMINAL' ? 96 : 42, description: 'Error rate & timeout adherence', signalsCount: 18 },
          { name: 'Capacity', score: sc.status === 'NOMINAL' ? 94 : 28, description: 'Thread pool & queue saturation limits', signalsCount: 12 },
          { name: 'Security', score: 97, description: 'TLS negotiation & cipher policy compliance', signalsCount: 9 },
        ],
        scoringPhilosophy: 'Score calculated via weighted multi-dimension causal health function: [Performance 35% + Reliability 35% + Capacity 20% + Security 10%] with hard ceiling penalties triggered by active Root Cause Anomalies.',
      },
      activeIncidents:
        sc.status === 'NOMINAL'
          ? []
          : [
              {
                id: 'INC-DEMO-001',
                title: sc.name,
                severity: sc.status === 'CRITICAL' ? 'CRITICAL' : 'HIGH',
                businessService: sc.businessImpact.impactedService || 'PaymentService',
                environment: 'DEMO',
                startedAt: new Date(Date.now() - 3600000).toISOString(),
                status: 'ACTIVE',
                rca: {
                  summary: sc.rca.summary,
                  confidencePercent: sc.rca.confidencePercent,
                  evidenceCount: sc.causalStory.length,
                },
              },
            ],
    };
  }

  public async getLiveRequests(filter?: VitalisLiveRequestsFilter): Promise<VitalisRequest[]> {
    const sc = this.activeScenario;
    const isError = sc.status !== 'NOMINAL';

    return [
      {
        id: 'req_demo_01_master_pay',
        transactionType: 'POST /api/v1/payments/process',
        businessService: sc.businessImpact.impactedService || 'PaymentGateway',
        environment: 'DEMO',
        provenance: 'SIMULATED',
        status: isError ? 'INCIDENT' : 'HEALTHY',
        startedAt: new Date(Date.now() - 25000).toISOString(),
        durationMs: sc.p95LatencyMs,
        statusCode: isError ? 500 : 200,
        currentHop: isError ? 'IBM DB2 Enterprise Database' : 'Payment Settlement Gateway',
        spans: sc.journey.map((hop, idx) => ({
          id: `span_demo_${idx}`,
          name: hop.name,
          subsystem: hop.kind,
          tier: hop.kind as any,
          durationMs: parseInt(hop.time) || 4,
          error: hop.status === 'CRITICAL',
          statusCode: hop.status === 'CRITICAL' ? 500 : 200,
        })),
        causalChain: {
          cause: sc.causalStory[0]?.changeOrSignal || 'Baseline',
          effect: sc.causalStory[sc.causalStory.length - 1]?.observedEffect || 'Normal',
          confidencePercent: sc.rca.confidencePercent,
        },
        learningMemory: {
          patternId: 'PAT-DEMO-DB2-LOCK',
          occurrences: 4,
          recommendedAction: sc.rca.recommendedAction,
        },
      },
    ];
  }

  public async getApplicationInventory(): Promise<VitalisInventoryItem[]> {
    return [
      {
        id: 'srv_websphere_01',
        name: 'IBM WebSphere Application Server v9.0.5',
        runtime: 'Java 17 / Liberty Core',
        version: '9.0.5.14',
        environment: 'DEMO',
        status: this.activeScenario.status === 'CRITICAL' ? 'CRITICAL' : 'HEALTHY',
        subsystemsCount: 4,
        p95LatencyMs: this.activeScenario.status === 'CRITICAL' ? 2800 : 6,
        signalsFreshnessSec: 2,
        collectors: ['WebSphere JMX Collector', 'PMI Agent', 'WSSecurity Inspector'],
      },
      {
        id: 'srv_mq_01',
        name: 'IBM MQ Queue Manager QM_PAYMENT',
        runtime: 'IBM MQ Enterprise v9.3',
        version: '9.3.0.5',
        environment: 'DEMO',
        status: this.activeScenario.status === 'CRITICAL' ? 'DEGRADED' : 'HEALTHY',
        subsystemsCount: 2,
        p95LatencyMs: this.activeScenario.status === 'CRITICAL' ? 1400 : 3,
        signalsFreshnessSec: 2,
        collectors: ['IBM MQ Channel Monitor', 'PCF Inquirer'],
      },
      {
        id: 'srv_db2_01',
        name: 'IBM DB2 Enterprise Server Database',
        runtime: 'DB2 LUW Linux 64-bit',
        version: '11.5.8.0',
        environment: 'DEMO',
        status: this.activeScenario.status === 'CRITICAL' ? 'CRITICAL' : 'HEALTHY',
        subsystemsCount: 3,
        p95LatencyMs: this.activeScenario.status === 'CRITICAL' ? 4120 : 4,
        signalsFreshnessSec: 1,
        collectors: ['DB2 Mon Snapshot', 'SYSIBMADM Collector', 'db2diag Tailer'],
      },
    ];
  }

  public async getInvestigationRequest(req: VitalisInvestigationRequest): Promise<VitalisRequest> {
    const list = await this.getLiveRequests();
    return list[0];
  }
}
